### ISSUE TITLE
CPU and GPU via opencl - same speed 

### ISSUE THREAD

**Issue by tivvit** [Theano/libgpuarray#176]
Hi,

maybe I am just confused, but I would expect, that this would run faster on GPU.

`check2.py` from the docs http://deeplearning.net/software/theano/tutorial/using_gpu.html#id1

``` python
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')
```

Run on GPU with use of opencl

``` sh
THEANO_FLAGS=device=opencl0:1,floatX=float32,mode=FAST_RUN python check2.py
Mapped name None to device opencl0:1: HD Graphics 4000
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, (False,))>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 2.739221 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the gpu
```

compared to CPU (which is almost the same)

``` sh
THEANO_FLAGS=device=cpu,floatX=float32,mode=FAST_RUN python check2.py
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 2.618953 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu
```

Latest version of Theano and libgpuarray on MacBook Pro Late 2012 with Intel HD Graphics 4000.

**Comment by abergeron** [comment]
This would be more of a Theano question than a libgpuarray question.

But to answer it: The OpenCL support in Theano is still very much in alpha.  It could be that some op is not implemented in that graph.  Or it could be that some op is still implemented in a naive way.  To make sure a profile would be required (with profile=True), 

However it would still be widely inaccurate due to the non-blocking nature of the backend.  This can be alleviated with the gpuarray.sync flag, but not all ops respect it.  So be aware of that before make any conclusions about what is slow and what isn't.

**Comment by nouiz** [comment]
closing, we don't have good opencl support for now. there is another issue about that.
