### ISSUE TITLE
New branch that would have the older version

### ISSUE THREAD

**Issue by Sentient07** [Theano/libgpuarray#183]
From the discussion [here ](https://groups.google.com/d/msg/theano-users/TkWxtMFuork/RV2w3QDsHQAJ) i feel it would be better to have a branch(say v9998) that has the older version of the GPUArray(-9998), as there might be other developers who are working on branches that needs the older version which they don't want to rebase with the current theano-master. 
cc : @nouiz @lamblin

**Comment by abergeron** [comment]
I'm not sure we want to maintain two different versions.  There won't be any work done on the older version of libgpuarray.

I don't really see any real arguments against rebasing since if there aren't any conflicts, it's easy and if there are conflicts, then you'll have to do it anyway before it gets merged.

Also, this is a temporary situation that should resolve itself as with time since all future development should happen on the latest version.  There is also a smaller risk of this happening again since one of the major changes was to revise the external api to be more robust to internal changes, which should remove the need for another major version bump in the future (hopefully).

**Comment by nouiz** [comment]
tag to the old version could be useful. But I would do that only if the
rebase don't work well. So keep us updated on That.

**Comment by Sentient07** [comment]
@nouiz @abergeron , As a regular user, one would install stable version of theano, which is 0.8.2. That version, as @lamblin said is linked to the older version of libgpuarray. It would be compelling users to use bleeding edge version and hence i felt we have to support the older version of GPU array as well

**Comment by abergeron** [comment]
In that case I suppose we could have a tag to help people install the right version.  But I don't want to maintain multiple branches.

**Comment by Sentient07** [comment]
@abergeron I installed libgpuarray from github and not pip so i didn't know to specify the version. Do we have an option to install libgpuarray from pip?

**Comment by abergeron** [comment]
With a tag or commit hash it can be done, using something like this: https://coderwall.com/p/-wbo5q/pip-install-a-specific-github-repo-tag-or-branch

**Comment by nouiz** [comment]
What about creating tag like Theano-0.8.2 that would be the most recent
commit in ligpuarray that support that Theano version?

**Comment by abergeron** [comment]
There is now the tag https://github.com/Theano/libgpuarray/releases/tag/v-9998 that should be compatible with Theano-0.8.2.

**Comment by nouiz** [comment]
We should document that somewhere.

**Comment by abergeron** [comment]
Yes, probably somewhere in the Theano docs.
