### ISSUE TITLE
No test device specified.  Specify one using the DEVICE or GPUARRAY_TEST_DEVICE environment variables.

### ISSUE THREAD

**Issue by meatcomputer** [Theano/libgpuarray#246]
I tried setting DEVICE=cuda0 and now my python kernel dies. What should this value be?

**Comment by abergeron** [comment]
These variables are for running the test suite.  What are you trying to do?

**Comment by meatcomputer** [comment]
I'm trying to get the new gpuarray backend working for theano. When I set device = cuda in .theanorc, importing theano crashes iPython. I was hoping I could run the test suite and resolve why.

**Comment by abergeron** [comment]
Please copy and paste the commands you ran and the output in the terminal.

**Comment by meatcomputer** [comment]
import pygpu
pygpu.test()
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

**Comment by abergeron** [comment]
Can you try to run this outside of ipython notebook and see the terminal output?

**Comment by meatcomputer** [comment]
![image](https://cloud.githubusercontent.com/assets/2209906/18213221/c37d7f20-710c-11e6-96cf-b8918db0d787.png)

**Comment by abergeron** [comment]
Are you using the latest version of pygpu?

**Comment by meatcomputer** [comment]
Not sure how to determine that. I have the version that exits in the master branch of this project.

**Comment by abergeron** [comment]
This problem seems like one we had before where mismatched versions of pygpu and libgpuarray would instantly crash on context initialization.

This was fixed about four months ago, which is why I asked the question.

If you are sure this is not the case, then the next step is to run under a debugger and try to figure out why it crashes.  You can make a debug build to help with that by using the build type `Debug` instead of `Release`.

**Comment by abergeron** [comment]
I will assume that this is fixed since I haven't heard anything back.
