### ISSUE TITLE
pygpu was configured but could not be imported 

### ISSUE THREAD

**Issue by johnbie** [Theano/libgpuarray#253]
Sorry if this is a trivial problem!!! I am new to linux environment as a whole and running into problems left and right!!

I'm trying to run gputest.py from dennybritz/nn-theano, but I have been unable to run with GPU. I got it running via CPU, but couldn't get further than that.

I exported following flag:
export THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32

ran python gputest.py

and got following output:
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/gpuarray/init.py", line 20, in
import pygpu
ImportError: No module named pygpu
[Elemwise{exp,no_inplace}()]
Looping 100 times took 2.73069596291 seconds
Result is [ 1.23178029 1.61879337 1.52278066 ..., 2.20771813 2.29967761
1.62323284]
Used the cpu.

Other information:
Can't access or don't know how to use nvidia-smi command.
All the packages are running the latest versions from what I know.
There has been hash security issue when attempting to install CUDA.
Ran the code using python 2.7.
For some reason I don't have the CUDA folder in /usr/local.
I have anaconda for python 2.x and python 3.x.
I may have installed CUDA from both nvidia and apt-get.

Please tell me if there's any more information I need to provide.

**Comment by slefrancois** [comment]
A first step would be to ensure CUDA is installed properly. It probably isn't if nvidia-smi doesn't work.

The apt package for CUDA 7.5 won't install on Ubuntu 16 because of a weak hash. CUDA 8 RC installs with a warning, but works. Alternatively, you can install the .run package which does not check hashes. Also make sure you install the NVIDIA display driver from the package, and add the CUDA paths to your environment as specified in the CUDA install docs.

Once you have CUDA installed, try the libgpuarray and pygpu installation again and make sure you can import pygpu. 

Also, for user support, I encourage you to use the mailing list theano-users@googlegroups.com. I will close the issue and you can email there if you need further support.
