### ISSUE TITLE
Problem at cmake .. -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by divinekage** [Theano/libgpuarray#259]
Hi,

Below are my errors at the point of doing cmake .. -DCMAKE_BUILD_TYPE=Release

C:\Users\Leonard\libgpuarray\Build>cmake .. -DCMAKE_BUILD_TYPE=Release
-- Could NOT find CLBLAS (missing:  CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIRS)
-- Could NOT find NCCL (missing:  NCCL_LIBRARY NCCL_INCLUDE_DIR)
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Checking for one of the modules 'check'
Tests disabled because Check was not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "gpuarray" in directory C:/Users/Leonard/libgpuarray/src
    linked by target "gpuarray-static" in directory C:/Users/Leonard/libgpuarray/src
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "gpuarray" in directory C:/Users/Leonard/libgpuarray/src
    linked by target "gpuarray-static" in directory C:/Users/Leonard/libgpuarray/src

-- Configuring incomplete, errors occurred!
See also "C:/Users/Leonard/libgpuarray/Build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Leonard/libgpuarray/Build/CMakeFiles/CMakeError.log".

Could anyone assist?

**Comment by divinekage** [comment]
I am quite confused, i am supposed to put 'clblas', 'nccl', and 'check' in which folders?

**Comment by abergeron** [comment]
clBLAS, check and NCCL are optional so you don't need to put them anywhere if you don't want to use them.

 * clBLAS is for bias ops for OpenCL
 * check is the unit tests in C
 * NCCL is for collective operations on multiple GPUs (like allreduce)

However cuBLAS is required to compile the cuda stuff and should come with the runtime.  Could you remove the Build directory and run cmake again so that I can see what failed?

**Comment by Sentient07** [comment]
Same problem I faced and I have posted in this [thread](https://groups.google.com/forum/#!topic/theano-dev/mtZ9zRQCCuI)(the last two email). CuBLAS is required to compile the cuda and you'll get that with CUDA 8.0 toolkit. Unfortunately, you've to download the whole toolkit instead of just that package.

**Comment by abergeron** [comment]
Since libgpuarray now does dynamic loading for the libraries it needs at runtime, you no longer need to install anything to build it.  You do need to install certain packages and libraries to be able to use the connected backends though.
