### ISSUE TITLE
Accessing gpudata device pointer in C++

### ISSUE THREAD

**Issue by aam-at** [Theano/libgpuarray#390]
I am working to extend theano using third-party cuda library. The library requires passing a pointer to the data. Pygpu provides a convenient property `gpudata` to access a pointer which can be passed to a third-party library like scikit-cuda.

In C++, I encountered difficulties accessing a device pointer. Accessing member `devptr` fails due to forward declaration of `gpudata`. I tried to mimic access to a first member of struct in [pygpu](https://github.com/Theano/libgpuarray/blob/master/pygpu/gpuarray.pyx#L2145) using the following snippet:
```c++
float *A_ptr = (float *) ((void **)A->ga.data)[0];
```
However, thirdy-party library fails with either segmentation fault or an illegal memory access upon outputting result. Complete example can be found [here](https://github.com/aam-at/Theano/blob/magma_matrix_inverse/theano/gpuarray/magma_linalg.c#L67).

How can I access `gpudata` device pointer in C++?

**Comment by abergeron** [comment]
You have the right code to access the pointer.  (You can also use PyGpuArray_DEV_DATA since your code looks like a Theano Op).

I suspect that what is missing is setting the proper ambient context with cuda_enter() like what is done here: https://github.com/aam-at/Theano/blob/magma_matrix_inverse/theano/gpuarray/dnn_fwd.c#L88

Make sure to also exit the context with cuda_exit() before returning.

**Comment by aam-at** [comment]
@abergeron Thanks, that's resolved the issue. For someone who will come across this issue, you also need to call to `setup_ext_cuda()` in `#section init_code`.
