### ISSUE TITLE
Tensor op and alignment

### ISSUE THREAD

**Issue by borisfom** [Theano/libgpuarray#504]
CUDNN7 requires 128-bit (16 bytes, 0x7F mask) alignment for HMMA operations to be fast.
It would be great to enforce that kind of alignment in GPU allocator.
This is diagnostic from Theano debug run:
(using CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM (timed)(cache), ws:0, hash:FWD|GPU#0000:01:00.0 -t -g 1 -dim 2,3,10,9,270,90,9,1 -filt 5,3,7,7 -mode conv -pad 0,0 -subsample 1,1 -dilation 1,1 [unaligned])

**Comment by nouiz** [comment]
IRL discussion with @abergeron. Currently, it is aligned with 64 bytes. So this constrain is good. There is operation that can generate not aligned output like subtensors.

The base ptr will always be aligned to 64 bytes. It is the offset that can make it unaligned.

So we need to understand why this get generated.

Currently, if you use those Theano flags, you will get the offset information printed: profile=True,profile_memory=True (maybe you need to add config.profiling.n_apply=100 or bigger to have a more complete list).

This outptu isn't the most useful to parse, but it would help. Can you try that and send me the output?

If it don't help us enough, I can update theano.printing.debugprint() to print the extra information, but after the 0.7 release.

To better understand why this get generated, can you

**Comment by abergeron** [comment]
Yes, the current alignement is 64 bytes.  It was 16 bytes before but that made cublas crash so we bumped it up.

However, it is possible to get "unaligned" arrays through through the offset which can be set by things like indexing.

**Comment by abergeron** [comment]
I think I figured out why it always reports as unaligned.  You take the pointer and look for a mask of 0xff.  This means 2048 bits alignement (256 byte alignment) since this pointers are in bytes not bits.  Since almost none of the pointers respect that, it will almost always fail.

For a 128 bit alignement, the proper mask should be 0x0F (or 0x7 for float16 maybe).  With this change I see almost no "[unaligned]" mentions in the output.

I am not 100% sure that this is right though so I'm waiting for feedback from you before proceeding.

**Comment by borisfom** [comment]
You are right – please change to 0xF : float16 HMMA needs 128-bit alignment.

**Comment by abergeron** [comment]
I've made a PR at: https://github.com/Theano/Theano/pull/6456

Please make sure I have the mask correct since I don't understand why you had a check on the dtype before.

**Comment by nouiz** [comment]
fixed by https://github.com/Theano/Theano/pull/6456
