### ISSUE TITLE
Python 3.5.2: pygpu was configured but could not be imported or is too old (version 0.6 or higher required)

### ISSUE THREAD

**Issue by loretoparisi** [Theano/libgpuarray#536]
```
root@2ec43fec4281:~# python3 gpu_test.py 
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
NoneType
root@2ec43fec4281:~# python3 -c 'import pygpu; print(pygpu.__version__)'
0.7.2+23.gace45c6
root@2ec43fec4281:~# python3 -c 'import pygpu; print(pygpu.__path__)'
['/usr/local/lib/python3.5/dist-packages/pygpu-0.7.2+23.gace45c6-py3.5-linux-x86_64.egg/pygpu']
root@2ec43fec4281:~# python3 --version
Python 3.5.2
```

This could be related to https://github.com/Theano/libgpuarray/issues/421

**Comment by loretoparisi** [comment]
**[UPDATE]**

A workaround is

```
pip install -U git+https://github.com/Theano/Theano.git#egg=Theano
```

as mentioned in https://github.com/Theano/libgpuarray/issues/393

**Comment by abergeron** [comment]
This is not a workaround.  Theano 0.9 works with pygpu 0.6.X. The next release of Theano (and the current master) works with 0.7.X.

**Comment by loretoparisi** [comment]
@abergeron ok, so why doing `RUN pip3 install theano` it does not work?

**Comment by abergeron** [comment]
Because the current stable release is 0.9 so that is what you get with pip install.  You have pygpu 0.7.2+ installed so that is not compatible with the stable Theano.

If you want to use the stable release you can install pygpu 0.6.9, otherwise using the master as you did will also work.  I just wanted to note that this is not a "workaround" it's actually how it is supposed to work.

**Comment by msiraj83** [comment]
@loretoparisi ... thanks ... its work for me....
