### ISSUE TITLE
Return values of elemwise1, etc., are not cached

### ISSUE THREAD

**Issue by davidweichiang** [Theano/libgpuarray#68]
From #66:
I'm also wondering if you consider it an issue that ndgpuarray's `__add__` and friends recompile their kernels every single time (because they create a new `ElemwiseKernel`/`ReductionKernel` object and `self` is part of the cache key).

The workaround I implemented was to add another layer of caching around `elemwise1`, `elemwise2`, and `reduce1` that returns a cached `ElemwiseKernel`/`ReductionKernel` object if everything (context, operation, argument/result types) matches.

Another possibility would be to add `__hash__` and `__eq__` methods to `ElemwiseKernel`/`ReductionKernel` so that the cache can recognize when two kernel objects are equivalent. I believe that would be the simpler solution.

I'd be happy to try either of the above, or possibly something else if you have any ideas.

**Comment by abergeron** [comment]
Yes, I do.  The planned fix was to have a in-memory and on-disk cache at the C level for kernel compiles.  However since implementing a cache in C is much harder and there are no premade ones (that aren't GPL-licensed) then it kinda fell to the sidelines.

In the meantime adding __hash__ and __eq__ to ElemwiseKernel and ReductionKernel is the best idea I think.

**Comment by abergeron** [comment]
There is now an in-memory cache for all kernels which should speed up reuse of those kernels so I would consider this issue fixed.
